---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
      
    - name: Copy file with owner and permissions
      copy:
        src: /home/centos/docker_server/vars/testfile.txt
        dest: /home/centos/docker_server/vars/testfile.txt
